[platformio]
default_envs = controller, motor, single, calibration

[env]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
lib_deps =
  links2004/WebSockets
  bblanchon/ArduinoJson

[env:controller]
build_flags = -D DEVICE_ROLE_CONTROLLER
build_src_filter = +<main.cpp> -<calibration.cpp>

[env:motor]
build_flags = -D DEVICE_ROLE_MOTOR
build_src_filter = +<main.cpp> -<calibration.cpp>

[env:single]
build_flags = -D DEVICE_ROLE_SINGLE
build_src_filter = +<main.cpp> -<calibration.cpp>

[env:calibration]
build_src_filter = +<calibration.cpp> -<main.cpp>
